import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  groups: [
    { name: 'basic', title: 'Basic Details (അടിസ്ഥാന വിവരങ്ങൾ)' },
    { name: 'content', title: 'Content & Description (വിവരണങ്ങൾ)' },
    { name: 'media', title: 'Media & Gallery (ചിത്രങ്ങൾ)' },
    { name: 'links', title: 'Relationships & Links (ബന്ധപ്പെട്ട ലിങ്കുകൾ)' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Project Title',
      type: 'string',
      description: 'പ്രോജക്റ്റിന്റെ പേര് (e.g. Blood Donation Camp 2025)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('പ്രോജക്റ്റ് പേര് നൽകുക (Project title is required)'),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'വെബ്‌സൈറ്റ് യുആർഎൽ നിർണ്ണയിക്കാൻ ഉപയോഗിക്കുന്നു. (Used for URL mapping. Auto-generate from title.)',
      options: {
        source: 'title',
        maxLength: 96,
      },
      group: 'basic',
      validation: (Rule) => Rule.required().error('Slug ആവശ്യമാണ് (Slug is required)'),
    }),
    defineField({
      name: 'date',
      title: 'Project Date',
      type: 'date',
      description: 'പ്രോജക്റ്റ് നടന്ന തീയതി',
      group: 'basic',
      validation: (Rule) => Rule.required().error('തീയതി തിരഞ്ഞെടുക്കുക (Date is required)'),
    }),
    defineField({
      name: 'year',
      title: 'Year',
      type: 'number',
      description: 'പ്രോജക്റ്റ് വർഷം (ലിസ്റ്റുകൾ ക്രമീകരിക്കാൻ ഉപയോഗിക്കുന്നു, e.g., 2025)',
      group: 'basic',
      validation: (Rule) => Rule.required().integer().min(1982).max(2100).error('സാധുവായ വർഷം നൽകുക (Valid year is required)'),
    }),
    defineField({
      name: 'batch',
      title: 'Batch',
      type: 'reference',
      to: [{ type: 'batch' }],
      description: 'ഈ പ്രോജക്റ്റ് നടപ്പിലാക്കിയ ബാച്ച് (Select the batch that executed this project)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('ബാച്ച് തിരഞ്ഞെടുക്കുക (Batch association is required)'),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
      description: 'പ്രോജക്റ്റ് വിഭാഗം (Project category, e.g. Health, Environment)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('വിഭാഗം തിരഞ്ഞെടുക്കുക (Category is required)'),
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'പ്രോജക്റ്റ് നടന്ന സ്ഥലം (e.g., School Campus, local community center)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('സ്ഥലം നൽകുക (Location is required)'),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Completed (പൂർത്തിയായത്)', value: 'completed' },
          { title: 'Ongoing (നടന്നുകൊണ്ടിരിക്കുന്നത്)', value: 'ongoing' },
          { title: 'Planned (ആസൂത്രണം ചെയ്തത്)', value: 'planned' },
        ],
      },
      group: 'basic',
      validation: (Rule) => Rule.required().error('സ്റ്റാറ്റസ് തിരഞ്ഞെടുക്കുക (Status is required)'),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 2,
      description: 'ഹോംപേജിലും കാർഡുകളിലും കാണിക്കാനുള്ള ലളിതമായ ചെറു വിവരണം (Brief overview for project cards. 1-2 sentences.)',
      group: 'content',
      validation: (Rule) => Rule.required().max(200).error('ചെറുവിവരണം നിർബന്ധമാണ്, പരമാവധി 200 അക്ഷരങ്ങൾ (Summary is required, max 200 chars)'),
    }),
    defineField({
      name: 'description',
      title: 'Detailed Description',
      type: 'text',
      rows: 6,
      description: 'പ്രോജക്റ്റിന്റെ വിശദമായ വിവരണം (Detailed description of the project activities)',
      group: 'content',
      validation: (Rule) => Rule.required().error('വിശദമായ വിവരണം നിർബന്ധമാണ് (Detailed description is required)'),
    }),
    defineField({
      name: 'problemAddressed',
      title: 'Problem Addressed',
      type: 'text',
      rows: 4,
      description: 'പരിഹരിച്ച പ്രശ്നം അല്ലെങ്കിൽ എന്തിനാണ് ഈ പ്രോജക്റ്റ് ചെയ്തത് (What problem was the local community facing?)',
      group: 'content',
      validation: (Rule) => Rule.required().error('പരിഹരിച്ച പ്രശ്ന വിവരണം നൽകുക (Problem addressed description is required)'),
    }),
    defineField({
      name: 'whatNssDid',
      title: 'What NSS Did',
      type: 'text',
      rows: 4,
      description: 'പ്രശ്നം പരിഹരിക്കാൻ വളന്റിയർമാർ ചെയ്ത കാര്യങ്ങൾ (What actions were taken by the NSS volunteers?)',
      group: 'content',
      validation: (Rule) => Rule.required().error('വളന്റിയർമാരുടെ പ്രവർത്തന വിവരണം നൽകുക (What NSS did description is required)'),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      description: 'പ്രധാന ആകർഷകമായ ഫോട്ടോ. ലാൻഡ്‌സ്‌കേപ്പ് (landscape 16:9) അനുപാതം നിർബന്ധമാണ്.',
      options: {
        hotspot: true,
      },
      group: 'media',
      validation: (Rule) => Rule.required().error('കവർ ചിത്രം നിർബന്ധമാണ് (Cover image is required)'),
    }),
    defineField({
      name: 'images',
      title: 'Project Gallery / Additional Photos',
      type: 'array',
      description: 'പ്രോജക്റ്റുമായി ബന്ധപ്പെട്ട മറ്റ് ചിത്രങ്ങൾ (Other photos of volunteers during action. Avoid blurry ones!)',
      of: [{ type: 'imageAsset' }],
      group: 'media',
    }),
    defineField({
      name: 'impactMetrics',
      title: 'Project Impact Metrics',
      type: 'array',
      description: 'ഈ പ്രോജക്റ്റ് വഴിയുണ്ടായ നേട്ടങ്ങൾ (e.g. 50 Volunteers, 100 Trees Planted, 30 Units Blood)',
      of: [{ type: 'impactMetric' }],
      group: 'media',
      validation: (Rule) => Rule.required().min(1).error('കുറഞ്ഞത് ഒരു നേട്ടമെങ്കിലും രേഖപ്പെടുത്തുക (At least 1 impact metric is required)'),
    }),
    defineField({
      name: 'relatedCamp',
      title: 'Related Camp',
      type: 'reference',
      to: [{ type: 'camp' }],
      description: 'ഈ പ്രോജക്റ്റ് പ്രത്യേക ക്യാമ്പിന്റെ ഭാഗമായി ചെയ്തതാണെങ്കിൽ തിരഞ്ഞെടുക്കുക (Select if done during a 7-day Special Camp)',
      group: 'links',
    }),
    defineField({
      name: 'reports',
      title: 'Related Reports',
      type: 'array',
      description: 'ബന്ധപ്പെട്ട പിഡിഎഫ് റിപ്പോർട്ടുകൾ ഉണ്ടെങ്കിൽ ചേർക്കുക (Associated official reports)',
      of: [{ type: 'reference', to: [{ type: 'report' }] }],
      group: 'links',
    }),
    defineField({
      name: 'highlights',
      title: 'Related Highlights',
      type: 'array',
      description: 'പ്രധാന നേട്ടങ്ങളുടെ അടയാളപ്പെടുത്തലുകൾ (Link to highlights if this project earned recognition)',
      of: [{ type: 'reference', to: [{ type: 'highlight' }] }],
      group: 'links',
    }),
    defineField({
      name: 'organizers',
      title: 'Organizers / Coordinators',
      type: 'array',
      description: 'പ്രവർത്തനത്തിന് നേതൃത്വം നൽകിയവർ (Add organizers or coordinators)',
      of: [{ type: 'string' }],
      group: 'links',
      validation: (Rule) => Rule.required().min(1).error('പ്രവർത്തനത്തിന് നേതൃത്വം നൽകിയ ഒരാളുടെയെങ്കിലും പേര് ചേർക്കുക (At least 1 organizer is required)'),
    }),
    defineField({
      name: 'featured',
      title: 'Featured Project',
      type: 'boolean',
      description: 'ഇത് ഹോംപേജിൽ പ്രദർശിപ്പിക്കേണ്ട പ്രധാന പ്രോജക്റ്റാണെങ്കിൽ ടിക്ക് ചെയ്യുക.',
      initialValue: false,
      group: 'basic',
    }),
    defineField({
      name: 'campRelated',
      title: 'Camp Related',
      type: 'boolean',
      description: 'പ്രത്യേക ക്യാമ്പുമായി ബന്ധപ്പെട്ടതാണെങ്കിൽ ടിക്ക് ചെയ്യുക.',
      initialValue: false,
      group: 'links',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      date: 'date',
      category: 'category.title',
      media: 'coverImage',
    },
    prepare({ title, date, category, media }) {
      const formattedDate = date ? new Date(date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : ''
      return {
        title: title || 'Untitled Project',
        subtitle: `${formattedDate}${category ? ` | ${category}` : ''}`,
        media,
      }
    },
  },
})
