import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Website Configuration',
  type: 'document',
  groups: [
    { name: 'basic', title: 'Basic Information (അടിസ്ഥാന വിവരങ്ങൾ)' },
    { name: 'leadership', title: 'Leadership (ഭാരവാഹികൾ)' },
    { name: 'contact', title: 'Contact Details (ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ)' },
    { name: 'about', title: 'About Content (വിവരണങ്ങൾ)' },
  ],
  fields: [
    defineField({
      name: 'schoolName',
      title: 'School/Institution Name',
      type: 'string',
      description: 'വിദ്യാലയത്തിന്റെ മുഴുവൻ പേര് (e.g., KHMHSS Valakkulam)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('വിദ്യാലയത്തിന്റെ പേര് നിർബന്ധമാണ് (School name is required)'),
    }),
    defineField({
      name: 'unitName',
      title: 'NSS Unit Name',
      type: 'string',
      description: 'എൻ.എസ്.എസ് യൂണിറ്റ് പേര് (e.g., NSS Unit 466)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('യൂണിറ്റ് പേര് നിർബന്ധമാണ് (Unit name is required)'),
    }),
    defineField({
      name: 'motto',
      title: 'NSS Motto',
      type: 'string',
      description: 'എൻ.എസ്.എസ് ആപ്തവാക്യം. Default: "Not Me, But You"',
      group: 'basic',
      validation: (Rule) => Rule.required().error('ആപ്തവാക്യം നിർബന്ധമാണ് (Motto is required)'),
    }),
    defineField({
      name: 'location',
      title: 'Location Description',
      type: 'string',
      description: 'വിദ്യാലയം സ്ഥിതി ചെയ്യുന്ന സ്ഥലം (e.g., Valakkulam, Malappuram)',
      group: 'basic',
      validation: (Rule) => Rule.required().error('സ്ഥലം നിർബന്ധമാണ് (Location is required)'),
    }),
    defineField({
      name: 'academicYear',
      title: 'Current Academic Year',
      type: 'string',
      description: 'നിലവിലെ അധ്യയന വർഷം (e.g., 2025–26)',
      placeholder: 'e.g. 2025–26',
      group: 'basic',
      validation: (Rule) => Rule.required().error('അധ്യയന വർഷം നിർബന്ധമാണ് (Academic year is required)'),
    }),
    defineField({
      name: 'programmeOfficer',
      title: 'Programme Officer Name',
      type: 'string',
      description: 'പ്രോഗ്രാം ഓഫീസറുടെ പേര്',
      group: 'leadership',
      validation: (Rule) => Rule.required().error('പ്രോഗ്രാം ഓഫീസറുടെ പേര് നിർബന്ധമാണ് (Programme Officer name is required)'),
    }),
    defineField({
      name: 'volunteerSecretary',
      title: 'Volunteer Secretary Name',
      type: 'string',
      description: 'വളന്റിയർ സെക്രട്ടറിയുടെ പേര്',
      group: 'leadership',
      validation: (Rule) => Rule.required().error('വളന്റിയർ സെക്രട്ടറിയുടെ പേര് നിർബന്ധമാണ് (Volunteer Secretary name is required)'),
    }),
    defineField({
      name: 'email',
      title: 'Contact Email Address',
      type: 'string',
      description: 'ഔദ്യോഗിക ഇമെയിൽ വിലാസം',
      group: 'contact',
      validation: (Rule) => Rule.required().email().error('സാധുവായ ഇമെയിൽ വിലാസം നൽകുക (Valid email is required)'),
    }),
    defineField({
      name: 'phone',
      title: 'Contact Phone Number',
      type: 'string',
      description: 'ഔദ്യോഗിക ഫോൺ നമ്പർ (e.g., +91 9876543210)',
      group: 'contact',
      validation: (Rule) => 
        Rule.regex(/^\+?[0-9\s\-()]{10,20}$/, { name: 'phone' })
          .error('ശരിയായ ഫോൺ നമ്പർ നൽകുക (Please enter a valid phone number)'),
    }),
    defineField({
      name: 'mission',
      title: 'Mission Statement',
      type: 'text',
      rows: 3,
      description: 'ലക്ഷ്യ പ്രഖ്യാപനം (Our mission. Keep it under 3-4 sentences.)',
      group: 'about',
      validation: (Rule) => Rule.required().error('മിഷൻ വിവരണം നിർബന്ധമാണ് (Mission statement is required)'),
    }),
    defineField({
      name: 'vision',
      title: 'Vision Statement',
      type: 'text',
      rows: 3,
      description: 'വിഷൻ വിവരണം (Our vision. Keep it under 3-4 sentences.)',
      group: 'about',
      validation: (Rule) => Rule.required().error('വിഷൻ വിവരണം നിർബന്ധമാണ് (Vision statement is required)'),
    }),
    defineField({
      name: 'objectives',
      title: 'Objectives',
      type: 'array',
      description: 'യൂണിറ്റിന്റെ പ്രധാന ലക്ഷ്യങ്ങൾ (List at least 1 objective)',
      of: [{ type: 'string' }],
      group: 'about',
      validation: (Rule) => Rule.required().min(1).error('കുറഞ്ഞത് ഒരു ലക്ഷ്യമെങ്കിലും നൽകുക (At least 1 objective is required)'),
    }),
    defineField({
      name: 'history',
      title: 'Unit History / Background',
      type: 'text',
      rows: 8,
      description: 'യൂണിറ്റിന്റെ ചരിത്രവും പശ്ചാത്തലവും (Detailed history of our NSS unit)',
      group: 'about',
      validation: (Rule) => Rule.required().error('യൂണിറ്റ് ചരിത്രം നിർബന്ധമാണ് (Unit history is required)'),
    }),
    defineField({
      name: 'achievements',
      title: 'Key Historical Achievements',
      type: 'array',
      description: 'പ്രധാന നേട്ടങ്ങൾ (Key historic achievements or awards)',
      of: [{ type: 'string' }],
      group: 'about',
      validation: (Rule) => Rule.required().min(1).error('കുറഞ്ഞത് ഒരു നേട്ടമെങ്കിലും നൽകുക (At least 1 achievement is required)'),
    }),
  ],
  preview: {
    select: {
      title: 'unitName',
      subtitle: 'schoolName',
    },
    prepare({ title, subtitle }) {
      return {
        title: title || 'NSS Unit Configuration',
        subtitle: subtitle || 'KHMHSS Valakkulam',
      }
    },
  },
})
