/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as CampsIndexRouteImport } from './routes/camps.index'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects.$projectSlug'
import { Route as GalleryAlbumSlugRouteImport } from './routes/gallery.$albumSlug'
import { Route as CampsCampSlugRouteImport } from './routes/camps.$campSlug'
import { Route as BatchesBatchSlugRouteImport } from './routes/batches.$batchSlug'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsIndexRoute = CampsIndexRouteImport.update({
  id: '/camps/',
  path: '/camps/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/projects/$projectSlug',
  path: '/projects/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAlbumSlugRoute = GalleryAlbumSlugRouteImport.update({
  id: '/gallery/$albumSlug',
  path: '/gallery/$albumSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsCampSlugRoute = CampsCampSlugRouteImport.update({
  id: '/camps/$campSlug',
  path: '/camps/$campSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchSlugRoute = BatchesBatchSlugRouteImport.update({
  id: '/batches/$batchSlug',
  path: '/batches/$batchSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/highlights': typeof HighlightsRoute
  '/journey': typeof JourneyRoute
  '/notices': typeof NoticesRoute
  '/reports': typeof ReportsRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/videos': typeof VideosRoute
  '/batches/$batchSlug': typeof BatchesBatchSlugRoute
  '/camps/$campSlug': typeof CampsCampSlugRoute
  '/gallery/$albumSlug': typeof GalleryAlbumSlugRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/batches/': typeof BatchesIndexRoute
  '/camps/': typeof CampsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/highlights': typeof HighlightsRoute
  '/journey': typeof JourneyRoute
  '/notices': typeof NoticesRoute
  '/reports': typeof ReportsRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/videos': typeof VideosRoute
  '/batches/$batchSlug': typeof BatchesBatchSlugRoute
  '/camps/$campSlug': typeof CampsCampSlugRoute
  '/gallery/$albumSlug': typeof GalleryAlbumSlugRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/batches': typeof BatchesIndexRoute
  '/camps': typeof CampsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/highlights': typeof HighlightsRoute
  '/journey': typeof JourneyRoute
  '/notices': typeof NoticesRoute
  '/reports': typeof ReportsRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/videos': typeof VideosRoute
  '/batches/$batchSlug': typeof BatchesBatchSlugRoute
  '/camps/$campSlug': typeof CampsCampSlugRoute
  '/gallery/$albumSlug': typeof GalleryAlbumSlugRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/batches/': typeof BatchesIndexRoute
  '/camps/': typeof CampsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/highlights'
    | '/journey'
    | '/notices'
    | '/reports'
    | '/stories'
    | '/team'
    | '/videos'
    | '/batches/$batchSlug'
    | '/camps/$campSlug'
    | '/gallery/$albumSlug'
    | '/projects/$projectSlug'
    | '/batches/'
    | '/camps/'
    | '/gallery/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/highlights'
    | '/journey'
    | '/notices'
    | '/reports'
    | '/stories'
    | '/team'
    | '/videos'
    | '/batches/$batchSlug'
    | '/camps/$campSlug'
    | '/gallery/$albumSlug'
    | '/projects/$projectSlug'
    | '/batches'
    | '/camps'
    | '/gallery'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/highlights'
    | '/journey'
    | '/notices'
    | '/reports'
    | '/stories'
    | '/team'
    | '/videos'
    | '/batches/$batchSlug'
    | '/camps/$campSlug'
    | '/gallery/$albumSlug'
    | '/projects/$projectSlug'
    | '/batches/'
    | '/camps/'
    | '/gallery/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HighlightsRoute: typeof HighlightsRoute
  JourneyRoute: typeof JourneyRoute
  NoticesRoute: typeof NoticesRoute
  ReportsRoute: typeof ReportsRoute
  StoriesRoute: typeof StoriesRoute
  TeamRoute: typeof TeamRoute
  VideosRoute: typeof VideosRoute
  BatchesBatchSlugRoute: typeof BatchesBatchSlugRoute
  CampsCampSlugRoute: typeof CampsCampSlugRoute
  GalleryAlbumSlugRoute: typeof GalleryAlbumSlugRoute
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  CampsIndexRoute: typeof CampsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps/': {
      id: '/camps/'
      path: '/camps'
      fullPath: '/camps/'
      preLoaderRoute: typeof CampsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$albumSlug': {
      id: '/gallery/$albumSlug'
      path: '/gallery/$albumSlug'
      fullPath: '/gallery/$albumSlug'
      preLoaderRoute: typeof GalleryAlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps/$campSlug': {
      id: '/camps/$campSlug'
      path: '/camps/$campSlug'
      fullPath: '/camps/$campSlug'
      preLoaderRoute: typeof CampsCampSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchSlug': {
      id: '/batches/$batchSlug'
      path: '/batches/$batchSlug'
      fullPath: '/batches/$batchSlug'
      preLoaderRoute: typeof BatchesBatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HighlightsRoute: HighlightsRoute,
  JourneyRoute: JourneyRoute,
  NoticesRoute: NoticesRoute,
  ReportsRoute: ReportsRoute,
  StoriesRoute: StoriesRoute,
  TeamRoute: TeamRoute,
  VideosRoute: VideosRoute,
  BatchesBatchSlugRoute: BatchesBatchSlugRoute,
  CampsCampSlugRoute: CampsCampSlugRoute,
  GalleryAlbumSlugRoute: GalleryAlbumSlugRoute,
  ProjectsProjectSlugRoute: ProjectsProjectSlugRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  CampsIndexRoute: CampsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
