/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects_'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as GalleryRouteImport } from './routes/gallery_'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampsRouteImport } from './routes/camps_'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects.$projectSlug'
import { Route as GalleryAlbumSlugRouteImport } from './routes/gallery.$albumSlug'
import { Route as CampsCampSlugRouteImport } from './routes/camps.$campSlug'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects_',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery_',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps_',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/projects/$projectSlug',
  path: '/projects/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAlbumSlugRoute = GalleryAlbumSlugRouteImport.update({
  id: '/gallery/$albumSlug',
  path: '/gallery/$albumSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsCampSlugRoute = CampsCampSlugRouteImport.update({
  id: '/camps/$campSlug',
  path: '/camps/$campSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/journey': typeof JourneyRoute
  '/notices': typeof NoticesRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/videos': typeof VideosRoute
  '/camps/$campSlug': typeof CampsCampSlugRoute
  '/gallery/$albumSlug': typeof GalleryAlbumSlugRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/journey': typeof JourneyRoute
  '/notices': typeof NoticesRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/videos': typeof VideosRoute
  '/camps/$campSlug': typeof CampsCampSlugRoute
  '/gallery/$albumSlug': typeof GalleryAlbumSlugRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/camps_': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/gallery_': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/journey': typeof JourneyRoute
  '/notices': typeof NoticesRoute
  '/projects_': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/videos': typeof VideosRoute
  '/camps/$campSlug': typeof CampsCampSlugRoute
  '/gallery/$albumSlug': typeof GalleryAlbumSlugRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/camps'
    | '/contact'
    | '/gallery'
    | '/highlights'
    | '/journey'
    | '/notices'
    | '/projects'
    | '/reports'
    | '/stories'
    | '/support'
    | '/team'
    | '/videos'
    | '/camps/$campSlug'
    | '/gallery/$albumSlug'
    | '/projects/$projectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/camps'
    | '/contact'
    | '/gallery'
    | '/highlights'
    | '/journey'
    | '/notices'
    | '/projects'
    | '/reports'
    | '/stories'
    | '/support'
    | '/team'
    | '/videos'
    | '/camps/$campSlug'
    | '/gallery/$albumSlug'
    | '/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/camps_'
    | '/contact'
    | '/gallery_'
    | '/highlights'
    | '/journey'
    | '/notices'
    | '/projects_'
    | '/reports'
    | '/stories'
    | '/support'
    | '/team'
    | '/videos'
    | '/camps/$campSlug'
    | '/gallery/$albumSlug'
    | '/projects/$projectSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CampsRoute: typeof CampsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HighlightsRoute: typeof HighlightsRoute
  JourneyRoute: typeof JourneyRoute
  NoticesRoute: typeof NoticesRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  StoriesRoute: typeof StoriesRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  VideosRoute: typeof VideosRoute
  CampsCampSlugRoute: typeof CampsCampSlugRoute
  GalleryAlbumSlugRoute: typeof GalleryAlbumSlugRoute
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_': {
      id: '/projects_'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery_': {
      id: '/gallery_'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps_': {
      id: '/camps_'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$albumSlug': {
      id: '/gallery/$albumSlug'
      path: '/gallery/$albumSlug'
      fullPath: '/gallery/$albumSlug'
      preLoaderRoute: typeof GalleryAlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps/$campSlug': {
      id: '/camps/$campSlug'
      path: '/camps/$campSlug'
      fullPath: '/camps/$campSlug'
      preLoaderRoute: typeof CampsCampSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CampsRoute: CampsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HighlightsRoute: HighlightsRoute,
  JourneyRoute: JourneyRoute,
  NoticesRoute: NoticesRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  StoriesRoute: StoriesRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  VideosRoute: VideosRoute,
  CampsCampSlugRoute: CampsCampSlugRoute,
  GalleryAlbumSlugRoute: GalleryAlbumSlugRoute,
  ProjectsProjectSlugRoute: ProjectsProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
